#99 render stacked bars
MajaLinder/SEMFIRE pull request #134
Opened 2022-11-29 15:00 UTC by b4rdha

#99  Added functionality of applying color by, so rendering stacked bars which a bar is composed of.

2022-11-29 15:15 UTC, MajaLinder commented
Nice work @b4rdha! I noticed that the colors are reversed compared to the bar chart
![image](https://user-images.githubusercontent.com/63287192/204567676-beb7f5eb-74ab-4b4c-9b4c-efeb0912237f.png)

2022-11-29 16:44 UTC, b4rdha commented
> Nice work @b4rdha! I noticed that the colors are reversed compared to the bar chart ![image](https://user-images.githubusercontent.com/63287192/204567676-beb7f5eb-74ab-4b4c-9b4c-efeb0912237f.png)

Ah good catch, I missed it when I pushed, I fixed it now thanks!

2022-11-29 16:47 UTC, MajaLinder approved these changes

2022-11-29 17:35 UTC, AstridBer reviewed
Great work! So nice to finally have this! 😄 

I tried to run the code and everything seems to work well. But I noticed that if the ColorBy is "none" then the hardcoded value is used instead of the value provided by the api. In the picture below the color of the bars should be orange instead of blue.
![colorByDefaultColor](https://user-images.githubusercontent.com/63287104/204601199-0e6c8ed9-c86e-46ba-abf4-60f0f7f93089.png)

2022-11-29 17:35 UTC, AstridBer commented on src/stackedBars.ts
> +    console.log(colorKeys);
Can the console.log be removed?

2022-11-29 17:52 UTC, AstridBer commented
Another thing that I noticed is that there is some strange behaviour when you mark a bar. I know this will be adressed in another issue but I think it is good to mention.

It seems like the pareto marks based on the color. In this picture you can compare how the built in visulaization reacts compared to the pareto.
![MarksByColor](https://user-images.githubusercontent.com/63287104/204602178-264789bf-f1eb-46f3-94c4-38e596f1422a.png)

If I however mark the "first color" nothing is marked in the pareto. 
![Doesn'tMarkFirstValue](https://user-images.githubusercontent.com/63287104/204602791-a3298ba2-b988-4ee6-a0a4-229c12c654b8.png)

Does anyone have any idea why this happens?

2022-11-30 07:47 UTC, MajaLinder requested changes
Before merging, I think we should go through Astrid's findings.

2022-11-30 09:06 UTC, MajaLinder commented
I found another issue. When adding two color by, the bars are not rendering in the correct order, so maybe something is wrong with how everything is rendered?

![image](https://user-images.githubusercontent.com/63287192/204753062-fbb34355-2d94-4c9a-af24-c7cb5c03c40a.png)

2022-11-30 09:16 UTC, MajaLinder requested changes
After the merge the padding on the right side of the chart disappeared

![image](https://user-images.githubusercontent.com/63287192/204755818-90ba410a-085c-4215-bd2b-82a7007b92e8.png)

2022-11-30 09:47 UTC, MajaLinder approved these changes

2022-11-30 09:49 UTC, merged